# Generated by Django 4.1.7 on 2023-04-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("breed", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=250)),
                ("age", models.IntegerField(default=0)),
            ],
        ),
    ]
